server:
  servlet.context-path: /auth
spring:
  h2.console:
    enabled: true
    path: /h2
  datasource.url: jdbc:h2:file:C:/db/data
#security:
#  oauth2:
#    client:
#      client-id: client
#      client-secret: secret